spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name : serie-service
  data:
    mongodb:
      port: 27017
      database: serie
      host: localhost
  main:
    allow-bean-definition-overriding: true