CREATE TABLE IF NOT EXISTS FILIAL(ID INT AUTO_INCREMENT PRIMARY KEY, NOME_FILIAL VARCHAR(100) NOT NULL,
RUA VARCHAR(100) NOT NULL, NUMERO INT NOT NULL, CIDADE VARCHAR(100) NOT NULL, ESTADO VARCHAR(100) NOT NULL,
CINCO_ESTRELA BOOLEAN)