version: '3.2'

services:
  zipkin-service:
    image: openzipkin/zipkin:2
    container_name: zipkin-service
    ports:
      - 9411:9411
  rabbit-service:
    image: rabbitmq:3-management
    container_name: rabbit-service
    ports:
      - 5672:5672
      - 15672:15672
  eureka-server:
    build: eureka
    container_name: eureka-server
    depends_on:
      - zipkin-service
    ports:
      - 8761:8761
  config-server:
    build: config
    container_name: config-server
    depends_on:
      - eureka-server
    ports:
      - 8888:8888
  gateway-server:
    build: gateway
    container_name: gateway-server
    depends_on:
      - config-server
    ports:
      - 8080:8080
  movie-server:
    build: movie
    container_name: movie-server
    depends_on:
      - config-server
    ports:
      - 8001:8001
  serie-server:
    build: serie
    container_name: serie-server
    depends_on:
      - config-server
    ports:
      - 8003:8003
  catalog-server:
    build: catalog
    container_name: catalog-server
    depends_on:
      - config-server
    ports:
      - 8001:8001
#    networks:
#      - host

#networks:
#  host:
#    driver: bridge