spring:
  config:
    import: optional:configserver:http://localhost:8888/
  application:
    name : catalog-service
  datasource:
    url: jdbc:mysql://${db_url}/movie
    username: ${db_username}
    password: ${db_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true