server:
  port: 8080
spring:
  application:
    name: api-gateway
    eureka:
      client:
        serverUrl:
          defaultZone: http://localhost:8761/eureka
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: apigateway
          uri: lb://DIGITAL-BANKING
          predicates:
            - Path=/digitalbank/v1/**
        - id: estoque
          uri: lb://ESTOQUE-SERVICE
          predicates:
            - Path=/estoque/v1/**
        - id: repositorio
          uri: lb://REPOSITORIO-SERVICE
          predicates:
            - Path=/repositorio/v1/**
          filters:
            - name: CircuitBreaker
              args:
                name: apigateway
                fallbackUri: forward:/fallback/usuarioFallback
            - name: CircuitBreaker
              args:
                name: estoque
                fallbackUri: forward:/fallback/estoqueFallback
            - name: CircuitBreaker
              args:
                name: repositorio
                fallbackUri: forward:/fallback/repositorioFallback

            - name: PreFiltroUsuario

resilience4j.circuitbreaker:
  configs:
    default:
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.util.concurrent.TimeoutException
        - java.io.IOException
  instances:
    apigateway:
      baseConfig: default
